feat: Add static portals
ChaosInitiative/Chaos-FGD pull request #104
Opened 2022-01-14 09:44 UTC by Smaedd

Adds the ability to mark a linked portal door as static, meaning that it will never move or turn off. This will allow light to be calculated for the world portal.

2022-01-14 14:40 UTC, hexaflexahexagon commented
Maybe add a note in the description saying this is required for light to travel through portals?

2022-01-26 10:03 UTC, Gocnak requested changes

2022-01-26 10:03 UTC, Gocnak commented on fgd/point/linked_portal_door.fgd
> +	isstatic(boolean) : "Static Portal" : 0 : "Does the portal never move or toggle?"
As hex suggested, adding some info about this being required for VRAD light to pass through the portal would be good"

```suggestion
	isstatic(boolean) : "Static Portal" : 0 : "If set to true, this portal does not ever move or toggle, and allows VRAD to cast light through it."
```

2022-01-27 01:51 UTC, Gocnak approved these changes

2022-01-27 02:28 UTC, braem approved these changes

2022-01-27 07:29 UTC, merged