Add trigger_momentum_promptinput
ChaosInitiative/Chaos-FGD pull request #131
Opened 2022-06-21 08:03 UTC by SlidyBat

Also some small associated changes to trigger_userinput

2022-06-26 22:54 UTC, braem approved these changes

2022-06-26 23:16 UTC, braem requested changes
I forgot to mention that this new entity will need to be added to db/factories/momentum.txt and fgd/visgroups.cfg

2022-06-27 04:19 UTC, braem approved these changes

2022-07-10 21:31 UTC, Gocnak commented on fgd/brush/trigger/trigger_momentum_promptinput.fgd
> +	]
Doesn't seem like it, other FGD files do not have a newline.

2022-07-10 21:34 UTC, Gocnak approved these changes

2022-07-10 21:34 UTC, merged