Consolidation of build scripts + github action
ChaosInitiative/Chaos-FGD pull request #32
Opened 2021-04-21 10:03 UTC by braem

Closes https://github.com/ChaosInitiative/Chaos-FGD/issues/21
Closes https://github.com/ChaosInitiative/Chaos-FGD/issues/23

Consolidates build scripts into one, with a menu, for both linux and windows.

Adds a github action that builds the FGD & copies folders over, using the new scripts. Has both linux and windows build jobs. 
Action also uploads an artifact for each job which contains only the built FGDs to speed up and lower size of upload (folders are just copied and so we can get them from the repo).

Also I found that linux and windows building is not the same. Linux specifically fails to have some `sphere(*)`'s present in the windows build. It's either a `unify_fgd.py` or srctools issue, which can be remedied later. For now it'd be best to use the windows artifact if for whatever reason we need it.

2021-04-23 22:41 UTC, Gocnak commented on .github/workflows/build.yml
> +        run: chmod +x ./install_srctools.sh && bash ./install_srctools.sh
We should probably commit this bash file permission. In Git Bash, do the chmod command, and you may also need to do `git update-index --chmod=+x install_srctools.sh`, and commit that.

2021-04-23 22:55 UTC, Gocnak approved these changes

2021-04-23 23:10 UTC, Gocnak requested changes
My bad I meant to reject, gotta fix up the .sh file then I'm good.

2021-04-24 00:32 UTC, braem commented
> 
> 
> My bad I meant to reject, gotta fix up the .sh file then I'm good.

I did & removed the chmod's from the workflow.

2021-04-24 00:35 UTC, Gocnak approved these changes

2021-04-24 00:36 UTC, merged